name: Compilar Reportes LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Verificacion de Compilacion PDF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        practica: [ "P1", "P2", "P3" ]
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Compilar PDF con latexmk
        uses: dante-ev/latex-action@edge
        with:
          root_file: Practicas/${{ matrix.practica }}/reporte.tex
          working_directory: Practicas/${{ matrix.practica }}/
          args: -pdf -interaction=nonstopmode -halt-on-error
