name: Verificacion de Compilacion PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verificacion:
    name: Verificacion de Compilacion PDF
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Compilar PDF con LaTeX
        uses: dante-ev/latex-action@edge
        with:
          root_file: reporte.tex
          working_directory: Practicas/P3/
          args: -pdf -interaction=nonstopmode
