name: Compilar Reporte LaTeX

# Se ejecuta cada vez que alguien hace un Pull Request hacia main
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Verificacion de Compilacion PDF
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Compilar documento principal
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: Practicas/P3
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
